# Generated by Django 3.1.3 on 2021-11-15 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankmate', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='question',
            new_name='document',
        ),
    ]
